---
- hosts: hqswitch
  gather_facts: yes

  vars:
    backuppath: "/home/awx/swbackup"

  tasks:
    - name: Backup switch (ios)
      ios_config:
        src : ios_template.j2
        backup: yes
        backup.options:
          filename: {{ ansible_host }}.cfg
          dir_path : /home/awx/
