---
- hosts: hqswitch
  gather_facts: yes

  vars:
    backuppath: "/backup"

  tasks:
    - name: Backup switch (ios)
      ios_config:
        backup: yes
      register: backup_location
      when: ansible_network_os == 'ios'

    - name: Backup switch (nxos)
      nxos_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}_{{ ansible_host }}.cfg"
          dir_path: "{{ backuppath }}"
      when: ansible_network_os == 'nxos'
